//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelSupply.DAL.Database_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.FuelHistories = new HashSet<FuelHistory>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public Nullable<int> KeyCustomerId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> FuelLimitType { get; set; }
        public Nullable<decimal> PaymentLimit { get; set; }
        public Nullable<decimal> AvailablePay { get; set; }
    
        public virtual CustomerType CustomerType1 { get; set; }
        public virtual FuelLimitType FuelLimitType1 { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual ICollection<FuelHistory> FuelHistories { get; set; }
    }
}
