//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelSupply.DAL.Database_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> FuelStationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FuelType { get; set; }
        public Nullable<decimal> FuelVolume { get; set; }
        public Nullable<decimal> FuelAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FuelStation FuelStation { get; set; }
        public virtual FuelType FuelType1 { get; set; }
        public virtual User User { get; set; }
    }
}
